version: "3.5"
services:
  orion:
    image: fiware/orion
    container_name: fiware-orion
    networks:
      - default
    links:
     - mongo-db
    hostname: orion
    depends_on:
      - mongo-db
    expose:
      - 1026
    ports:
      - 1026:1026 # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG
  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: mongo-db
    networks:
      - default
    expose:
      - 27017
    ports:
      - 27017:27017 # localhost:27017
  iota:
    image: my_ros_setup
    hostname: iota
    container_name: iota
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - 4061
    ports:
      - 4061:4061 # localhost:4041
      - "7000-8000:7000-8000" # localhost:7896
