site_name: IoT Agent ROS 2
site_url: 'https://fiware-ros2.readthedocs.org'
repo_url: 'https://github.com/FcoMelendez/iot-agent-ros2'
site_description: IoT Agent for ROS 2 Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions:
  - toc
  - fenced_code
use_directory_urls: false
theme: readthedocs
extra_css:
  - 'https://www.fiware.org/style/fiware_readthedocs.css'
  - 'https://www.fiware.org/style/fiware_readthedocs_iot.css'
pages:
  - Home: index.md
  - User & Programmers Manual:
      - API Walkthrough & Development intro: usermanual.md
  - Installation & Administration Manual:
      - Installation Guide: installationguide.md
      - Operations (Agent Use Cases): operations.md
